### ISSUE TITLE
Entering path on the linux cmd line is overridden by sad.ini

### ISSUE THREAD

**Issue by dantob** [tvrfan/EEC-IV-disassembler#3]
Its pulling the path from sad.ini, instead of using the path supplied on cmdline.
You can see that fldata.path is correct, but its not overriding the sad.ini settings. is sad.ini even needed at all anymore, can we just check same directory as binary for lst, msg, dir, cmt etc?

```
./SAD_4.0.5 /home/daniel/RAID/src/EEC-IV-disassembler/Linux/for.bin

**************************************************
EEC-IV disassembler Version 4.0.5 (25/02/2020)
Absolutely no warranty or liability
**************************************************


For binary file '/home/daniel/RAID/src/EEC-IV-disassembler/Linux/for.bin'
fn0: /home/user/EECDATA/bins/for.bin
fn1: /home/user/EECDATA/lists/for_lst.txt
fn2: /home/user/EECDATA/msgs/for_msg.txt
fn3: /home/user/EECDATA/dr_cm/for_dir.txt
fn4: /home/user/EECDATA/dr_cm/for_cmt.txt
fn5: ./sad.ini
fn6: /home/user/EECDATA/msgs/for_dbg.txt
bare: /home/daniel/RAID/src/EEC-IV-disassembler/Linux/
path: /home/daniel/RAID/src/EEC-IV-disassembler/Linux/
dpath: .
File not found or File error
```

**Comment by tvrfan** [comment]
Thanks for reporting
If you have everything in same directory with SAD, ini file is not necessary.   
I tend to split the bins, listings, and dir+cmts, in separate dirs which is why I added a config.

**Comment by dantob** [comment]
Thanks for the tip! Maybe move or rename _/Linux/sad.ini_ so it's not accidentally used by default.
Something like _sad.ini.example_ and move it to the _Docs_ folder?
