### ISSUE TITLE
SAD 4.0.5: RF0-E pointers don't always resolve to human names in 4 bank bins

### ISSUE THREAD

**Issue by dantob** [tvrfan/EEC-IV-disassembler#5]
For example:
Bank 1 is data bank, pseudocode shows wrong bank (bank 8, which is code only)
RF0 = 12060
> 0227a: a3,f1,64,06,4a     ldw   R4a,[**_Rf0+664_**]                 R4a = [**_826C4_**];

Should be:
> 0227a: a3,f1,64,06,4a     ldw   R4a,[**_Rf0+664_**]                 R4a = [**_126C4_**];

I'm also seeing cases like this, where values are correct, but human names still aren't applied:
RF2 = 126DC
> 86ea9: 45,e6,00,f2,40     ad3w  R40,**_Rf2,e6_**                   R40 = _**127C2**_;

Should be:
> 86ea9: 45,e6,00,f2,40 ad3w R40,Rf2,e6                                 R40 = TABLE_Spark_MBT;`

127C2 is defined as
> table 127C2 1282D "TABLE_Spark_MBT"              :Y X O +12 V +2 S

 (I'm seeing lots of regressions with 4.0.6L right now, I can open a separate report for that if you'd like)

**Comment by tvrfan** [comment]
Accepted.    Please email me at tvrfan99@gmail.com  with the list, I am already dealing with other issues this way.   I made quite a lot of changes for other issues, so may well be regression  bugs popping up.

**Comment by tvrfan** [comment]
didn't find error as such, but did find that the address is not checked in a command (xx_dir), and so putting the wrong bank in is NOT CORRECTED.  Need to add extra check against the data bank.

**Comment by tvrfan** [comment]
This should be fixed in latest release (4.0.7.1).    Added more checks in various places.
